repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
# -   repo: local
#     hooks:
#       - id: pytest
#         name: Run tests
#         entry: pytest
#         language: python
#         types: [python]
# env:
#     DB_HOST: localhost
#     DB_USER: hestiau
#     DB_PASSWORD: hestia
#     DB_NAME: hestia
