services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: bash -c "python manage.py install && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    # environment:
    #   - DB_SERVICE_HOST=db
    networks:
      - djangonetwork
  


  postgres:
    image: postgres:16-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    hostname: postgres
    # volumes:
    #   - data:/var/lib/postgresql/data
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
      POSTGRES_PASSWORD: hestia
      POSTGRES_USER: hestiau
      POSTGRES_DB: hestia
      
    ports:
      - 5432:5432
    networks:
      - djangonetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - djangonetwork
    depends_on:
      - postgres
networks:
  djangonetwork:
    driver: bridge

volumes:
  postgres_data: